-- MySQL Script generated by MySQL Workbench
-- Mon Oct 31 23:25:50 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP);


-- -----------------------------------------------------
-- Table `mydb`.`Cadastro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cadastro` (
  `Email` VARCHAR(50) NOT NULL,
  `Nome_Empresa` VARCHAR(50) NOT NULL,
  `Nome_Usuario` VARCHAR(45) NOT NULL,
  `CPF/CNPJ` VARCHAR(45) NOT NULL,
  `Senha` VARCHAR(45) NULL,
  `Login` INT NULL,
  PRIMARY KEY (`Email`),
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC) VISIBLE,
  UNIQUE INDEX `Nome_Empresa_UNIQUE` (`Nome_Empresa` ASC) VISIBLE,
  UNIQUE INDEX `Nome_Usuario_UNIQUE` (`Nome_Usuario` ASC) VISIBLE,
  UNIQUE INDEX `CPF/CNPJ_UNIQUE` (`CPF/CNPJ` ASC) VISIBLE,
  CONSTRAINT `id`
    FOREIGN KEY ()
    REFERENCES `mydb`.`user` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cadastro de Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cadastro de Produto` (
  `Nome do Produto` VARCHAR(25) NOT NULL,
  `Validade` DATE NULL,
  `Categoria` VARCHAR(45) NULL,
  `Marca` VARCHAR(45) NULL,
  `Preço por Quantidade` FLOAT NULL,
  `Preço pro Engradado` FLOAT NULL,
  `Fornecedor` VARCHAR(45) NULL,
  `Lote` INT NULL,
  PRIMARY KEY (`Nome do Produto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Login` (
  `idLogin` INT NOT NULL,
  `Cadastro_Email` VARCHAR(50) NOT NULL,
  `Senha` VARCHAR(45) NULL,
  PRIMARY KEY (`idLogin`),
  INDEX `fk_Login_Cadastro1_idx` (`Cadastro_Email` ASC) VISIBLE,
  CONSTRAINT `fk_Login_Cadastro1`
    FOREIGN KEY (`Cadastro_Email`)
    REFERENCES `mydb`.`Cadastro` (`Email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Produtos Cadastrados (Procura de itens)`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Produtos Cadastrados (Procura de itens)` (
  `Cadastrado` INT NOT NULL,
  `Nome_IMG` VARCHAR(90) NOT NULL,
  `Conteudo` TINYBLOB NOT NULL,
  `Tipo` VARCHAR(20) NOT NULL,
  `Tamanho` INT(10) UNSIGNED NOT NULL,
  `Cadastro de Produto_Nome do Produto` VARCHAR(25) NOT NULL,
  INDEX `fk_Produtos Cadastrados (Procura de itens)_Cadastro de Prod_idx` (`Cadastro de Produto_Nome do Produto` ASC) VISIBLE,
  PRIMARY KEY (`Cadastrado`),
  CONSTRAINT `fk_Produtos Cadastrados (Procura de itens)_Cadastro de Produto1`
    FOREIGN KEY (`Cadastro de Produto_Nome do Produto`)
    REFERENCES `mydb`.`Cadastro de Produto` (`Nome do Produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
